apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: helloworld-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: helloworld-volume
        configMap:
          name: helloworld-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helloworld-configmap
data:
  index.html: |
    <html>
      <head>
        <title>Hello World</title>
      </head>
      <body>
        <h1>Hello, Kubernetes!</h1>
      </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
